channels:
  - conda-forge
dependencies:
  - biopython
  - mdtraj
  - morfeus-ml # Version 0.8.0 was used to generate the database
  - numpy
  - openbabel
  - pandas
  - pooch
  - python>=3.10
  - requests
  - spyrmsd
  - tqdm
  - typing-extensions
