import argparse
from os import PathLike
from pathlib import Path
from tempfile import TemporaryDirectory
from contextlib import nullcontext
import sys
import traceback
import json

from gen_lib.utils import extract_file_from_zip, lock
from gen_lib.rotamer import Rotamer
from gen_lib.optimisation import get_opt_structures
from gen_lib.descriptors import calc_descriptors

# from gen_lib.data import CHARGES_AA


def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(
        "Optimise rotamer geometry and calculate descriptors on it"
    )
    parser.add_argument(
        "rotamer_id",
        type=str,
        help="ID of the rotamer",
    )
    parser.add_argument(
        "angles_json",
        type=Path,
        help="json file with the angles extracted from the Dunbrack library",
    )
    parser.add_argument(
        "xyz_zip",
        type=Path,
        help="path to the zipped xyz folder",
    )
    parser.add_argument(
        "-o",
        "--output_json",
        type=Path,
        help="optional path for output JSON file. If a folder, 'data.json' will be created inside. \
            If not specified, './data.json' will be used.",
        default=None,
    )
    args = parser.parse_args()

    return args.rotamer_id, args.angles_json, args.xyz_zip, args.output_json


def main(
    rotamer_id: str,
    angles_json: PathLike | str,
    xyz_zip: PathLike | str,
    run_path: PathLike | str | None = None,
    output_json: PathLike | str | None = None,
) -> None:
    """Optimise rotamer geometry and calculate descriptors on it.
    Args:
        rotamer_id: ID of the rotamer
        angles_json: json file with the angles extracted from the Dunbrack library
        xyz_zip: path to the zipped xyz folder
        run_path: path of folder in which to perform the full optimisation process
        output_json: path for output JSON file (if not provided, prints to stdout)
    Returns:
        None, writes data to prodided json file or stdout
    """

    if output_json is not None:
        output_json = Path(output_json)
        if output_json.is_dir():
            raise IsADirectoryError(
                f"Provided path {output_json} must be a file not a directory."
            )

    with open(angles_json, "r") as f:
        dunbrack_all_rotamers = json.load(f)
    dunbrack_data = dunbrack_all_rotamers[rotamer_id]

    try:
        rotamer = Rotamer(rotamer_id, dunbrack_data)

        already_calculated = False
        if output_json:
            with lock(output_json):
                already_calculated = rotamer.load_existing_sidechain(output_json)
            print(f"{rotamer_id} already calculated: {already_calculated}")

        if not already_calculated:
            temp_dir_context = (
                TemporaryDirectory() if run_path is None else nullcontext()
            )
            with temp_dir_context as temp_dir:
                run_folder = Path(temp_dir) if run_path is None else Path(run_path)
                if not run_folder.exists():
                    run_folder.mkdir(parents=True)

                # Extract non-optimised rotamer xyz file
                name_folder = Path(xyz_zip).stem
                pre_opt_xyz = run_folder / f"{rotamer_id}_pre_opt.xyz"
                extract_file_from_zip(
                    zip_archive=xyz_zip,
                    file_in_zip=f"{name_folder}/{rotamer_id}.xyz",
                    output_path=pre_opt_xyz,
                )

                # Optimise both whole rotamer and sidechain-H
                el_whole, coord_whole, el_sidechain, coord_sidechain = (
                    get_opt_structures(
                        dunbrack_data=dunbrack_data,
                        run_folder=run_folder,
                        rotamer_xyz=pre_opt_xyz,
                    )
                )
                rotamer.set_opt_geometries(
                    el_whole, coord_whole, el_sidechain, coord_sidechain
                )

            # Calculate descriptors
            # TODO: deal with a.a. generated by PeptideBuilder which should be charged
            # charge = CHARGES_AA[rotamer_key[0]]
            descriptors = calc_descriptors(el_sidechain, coord_sidechain)
            rotamer.descriptors = descriptors

        # Save as json
        if output_json:
            with lock(output_json):
                rotamer.to_json(output_json)
        else:
            sys.stdout.write(json.dumps(rotamer.to_dict(), indent=4))

    except Exception:
        # raise # Uncomment to see the error in the terminal as usual
        sys.stderr.write(f"*** Rotamer {rotamer_id}\n{traceback.format_exc()}\n")


if __name__ == "__main__":
    rotamer_id, angles_json, xyz_zip, output_json = parse_args()
    main(rotamer_id, angles_json, xyz_zip, output_json=output_json)
