from os import PathLike
from pathlib import Path
import subprocess
import shutil
from morfeus import read_xyz
from morfeus.typing import Array1DStr, Array2DFloat
from typing import Any
from PeptideBuilder import Geometry
import PeptideBuilder
from Bio.PDB import PDBIO
from openmm.app import PDBFile, Modeller
from openbabel import pybel
import os

from gen_lib.utils import get_atom_count
from gen_lib.constants import NUMBER_OF_CHI_ANGLES
from . import config


def gen_dihedral_constraints(
    dunbrack_data: dict[str, Any],
) -> list[tuple[list[int], float]]:
    """Generate the dihedral contraints for the specified whole rotamer.
    Args:
        dunbrack_data: data with angles extracted from the Dunbrack library
    Returns:
        list of tuples for dihedral constraints (1-based atom indices)
    """
    letter = dunbrack_data["letter"]

    # Indices of atoms follow the order generated by start_rotamer_xyz()
    N = 1
    CA = 5
    CB = 9
    G = 12
    chi1_constraint_G = ([N, CA, CB, G], dunbrack_data["chi1"])
    CG1 = 11
    chi1_constraint_G1 = ([N, CA, CB, CG1], dunbrack_data["chi1"])
    D = 15
    chi2_constraint_CD = ([CA, CB, G, D], dunbrack_data["chi2"])

    if letter in ["C", "S"]:
        dihedral_constraints = [chi1_constraint_G]
    elif letter in ["T", "V"]:
        dihedral_constraints = [chi1_constraint_G1]
    elif letter in ["D", "F", "H", "N", "W", "Y", "L"]:
        D1 = 14 if letter == "L" else 13
        dihedral_constraints = [
            chi1_constraint_G,
            ([CA, CB, G, D1], dunbrack_data["chi2"]),
        ]
    elif letter in ["I"]:
        CD1 = 18
        dihedral_constraints = [
            chi1_constraint_G1,
            ([CA, CB, CG1, CD1], dunbrack_data["chi2"]),
        ]
    elif letter in ["P"]:
        dihedral_constraints = [
            ([N, 4, 8, 11], dunbrack_data["chi1"]),
            ([4, 8, 11, 14], dunbrack_data["chi2"]),
            ([8, 11, 14, N], dunbrack_data["chi3"]),
        ]
    elif letter in ["E", "M", "Q"]:
        E = 16
        dihedral_constraints = [
            chi1_constraint_G,
            chi2_constraint_CD,
            ([CB, G, D, E], dunbrack_data["chi3"]),
        ]
    elif letter in ["K", "R"]:
        CE = 18
        Z = 21 if letter == "K" else 20
        dihedral_constraints = [
            chi1_constraint_G,
            chi2_constraint_CD,
            ([CB, G, D, CE], dunbrack_data["chi3"]),
            ([G, D, CE, Z], dunbrack_data["chi4"]),
        ]

    return dihedral_constraints


def gen_sidechain_constraint(
    dihedrals_rotamer: list[tuple[list[int], float]],
    aa_letter: str,
) -> list[tuple[list[int], float]]:
    """Adapt the constraints which are needed for H relaxation in sidechain-H
    Args:
        dihedrals_rotamer: list of dihedral constraints of the whole rotamer
        aa_letter: one-letter code of the amino acid
    Returns:
        chi2 (and chi3 for proline) constraints for the sidechain-H
    """
    if aa_letter in ["C", "S", "T", "V"]:
        raise ValueError(f"No chi angle kept in the side-chain of {aa_letter}.")
    elif aa_letter == "P":
        sidechain_constraints = [
            ([1, 2, 5, 8], dihedrals_rotamer[1][1]),
            ([2, 5, 8, 11], dihedrals_rotamer[2][1]),
        ]
    elif aa_letter == "I":
        sidechain_constraints = [([1, 2, 4, 11], dihedrals_rotamer[1][1])]
    else:
        sidechain_constraints = [
            (
                [a - b for a, b in zip(dihedrals_rotamer[1][0], (4, 7, 7, 7))],
                dihedrals_rotamer[1][1],
            )
        ]

    return sidechain_constraints


def write_xcontrol(
    file: PathLike | str,
    fixed_atoms: list[int] = None,
    dihedral_constraints: list[tuple[list[int], float]] = None,
    fc: float = 0.5,
    opt_engine: str | None = None,
) -> None:
    """Write input file for xTB optimisation with constraining or fixing
    Args:
        file: path to the input file to create
        fixed_atoms: list of atom indices to fix in space
        dihedral_constraints: list of tuples for dihedral constraints
            Each tuple should contain:
            - A list of exactly four atom indices (1-based) involved in the dihedral angle
            - A float specifying the desired dihedral angle in degrees
        fc: force constant for constraints (only used if `dihedral_constraints` is provided)
        opt_engine: optimisation engine to use
            - None uses xtb default engine: Approximate Normal Coordinate Rational Function optimizer (ANCopt)
            - "inertial": Fast Inertial Relaxation Engine (FIRE) (for cartesian coordinates)
    Returns:
        None, write input file
    """
    input = ""

    # Input block for dihedral constraints
    if dihedral_constraints:
        if not all(
            isinstance(item, tuple) and len(item) == 2 for item in dihedral_constraints
        ):
            raise ValueError(
                "For dihedral constraints, provide a list of tuples containing the angle and a list of atom indices."
            )

        input += "$constrain\n"
        input += f"   force constant={fc}\n"
        for atoms, angle in dihedral_constraints:
            if len(atoms) != 4:
                raise ValueError(
                    "Each dihedral constraint must have exactly 4 atom indices."
                )
            input += f"   dihedral: {', '.join(map(str, atoms))}, {angle}\n"
        input += "$end\n"

    # Input block for fixed atoms
    if fixed_atoms:
        if not all(isinstance(atom, int) for atom in fixed_atoms):
            raise ValueError("For fixing atoms, provide a list of fixed atom indices.")

        input += "$fix\n"
        input += f"   atoms: {','.join(map(str, fixed_atoms))}\n"
        input += "$end\n"

    # Input block for optimisation engine
    if opt_engine:
        input += "$opt\n"
        input += f"   engine={opt_engine}\n"
        input += "$end\n"

    # Write the input to the specified file
    with open(file, "w") as f:
        f.write(input)


def run_constraint_xtb(
    xyz_file: PathLike | str,
    path_run: PathLike | str,
    fixed_atoms: list[int] = None,
    dihedral_constraints: list[tuple[list[int], float]] = None,
    fc: float = 0.5,
    opt_engine: str | None = None,
    charge: int = 0,
    solvent: str = "ether",
) -> None:
    """Run constrained optimisation in implicit solvent with GFN2-xTB
    Args:
        xyz_file: xyz file for the starting structure
        path_run: folder to run the xTB optimisation (created if does not exist)
        fixed_atoms: list of atom indices to fix in space
        dihedral_constraints: list of tuples for dihedral constraints
            Each tuple should contain:
            - A list of exactly four atom indices (1-based) involved in the dihedral angle
            - A float specifying the desired dihedral angle in degrees
        fc: force constant for constraints (only used if `dihedral_constraints` is provided)
        opt_engine: optimisation engine to use
            - None uses xtb default engine: Approximate Normal Coordinate Rational Function optimizer (ANCopt)
            - "inertial": Fast Inertial Relaxation Engine (FIRE) (for cartesian coordinates)
        charge: charge of the molecule
        solvent: implicit solvent for the optimisation
    Returns:
        None, runs xTB optimisation
    """
    path_run = Path(path_run)
    # Create xcontrol file
    write_xcontrol(
        path_run / "xcontrol",
        fixed_atoms=fixed_atoms,
        dihedral_constraints=dihedral_constraints,
        fc=fc,
        opt_engine=opt_engine,
    )

    # Get absolute path of starting structure
    xyz_file = Path(xyz_file).resolve()

    # Run xtb from command line
    command = f"xtb {xyz_file} --opt --chrg {charge} --alpb {solvent} -I xcontrol"
    with open(path_run / "xtb.out", "w") as stdout, open(
        f"{path_run}/xtb.err", "w"
    ) as stderr:
        env = dict(os.environ)
        env["OMP_NUM_THREADS"] = f"{config.OMP_NUM_THREADS},1"
        env["MKL_NUM_THREADS"] = f"{config.OMP_NUM_THREADS}"
        env["OMP_STACKSIZE"] = config.OMP_STACKSIZE
        env["OMP_MAX_ACTIVE_LEVELS"] = str(config.OMP_MAX_ACTIVE_LEVELS)
        subprocess.run(
            command.split(),
            cwd=path_run,
            stdout=stdout,
            stderr=stderr,
            env=env,
        )


def replace_backbone(
    input_file: PathLike | str, output_file: PathLike | str, is_pro: bool = False
) -> None:
    """Replace the backbone of the rotamer by a H.
    Args:
        input_file: path to the input xyz file
        output_file: path to the output xyz file
        is_pro: whether the rotamer is a proline
            If True, both the backbone N and C alpha are replaced by Hs
    Returns:
        None, writes the modified structure to the output file
    """

    # Ensure that the output directory exists
    output_file = Path(output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Read in original structure
    with open(input_file, "r") as file:
        lines = file.readlines()

    # Replace the comment line
    lines[1] = "backbone replaced by H\n"

    if is_pro:
        # Replace backbone N with H
        atom_line = lines[2].split()
        atom_line[0] = "H"
        lines[2] = " ".join(atom_line) + "\n"

        # Replace C alpha with H
        atom_line = lines[5].split()
        atom_line[0] = "H"
        lines[5] = " ".join(atom_line) + "\n"

        # Delete rest of backbone atoms
        lines.pop(3)
        lines.pop(3)
        lines.pop(4)
        lines.pop(4)
        lines.pop(4)
        lines.pop(-1)

        # Move the H replacing N to the end of the file
        lines.append(lines.pop(2))

        nb_atoms_deleted = 6

    else:
        # Delete backbone N and the 3 bonded Hs
        lines.pop(2)
        lines.pop(2)
        lines.pop(2)
        lines.pop(2)

        # Replace C alpha with H
        atom_line = lines[2].split()
        atom_line[0] = "H"
        lines[2] = " ".join(atom_line) + "\n"

        # Delete backbone H alpha and COO
        lines.pop(3)
        lines.pop(3)
        lines.pop(3)
        lines.pop(-1)

        nb_atoms_deleted = 8

    # Update the atom count in the first line
    new_atom_count = int(lines[0].strip()) - nb_atoms_deleted
    lines[0] = f"{new_atom_count}\n"

    # Write the modified structure to the output file
    with open(output_file, "w") as output_file:
        output_file.writelines(lines)


def start_rotamer_xyz(
    dunbrack_data: dict[str, Any],
    xyz_output: PathLike | str,
    charge: int,
    tautomer: str = None,
) -> None:
    """Build initial rotamer geometry from Dunbrack dihedral angles.
    Args:
        dunbrack_data: data with angles extracted from the Dunbrack library
        xyz_output: path to XYZ file to create
        charge: charge of the rotamer
        tautomer: tautomer of the rotamer (only for histidine, either 'D' or 'E')
    Returns:
        None, writes the non-optimised rotamer geometry to the XYZ file
    """
    letter = dunbrack_data["letter"]

    # Build initial geometry from Dunbrack dihedral angles with PeptideBuilder
    # Results in a PDB file without hydrogens
    geo = Geometry.geometry(letter)
    geo.phi = dunbrack_data["phi"]
    geo.psi_im1 = dunbrack_data["psi"]
    if letter == "R":
        geo.N_CA_CB_CG_diangle = dunbrack_data["chi1"]
        geo.CA_CB_CG_CD_diangle = dunbrack_data["chi2"]
        geo.CB_CG_CD_NE_diangle = dunbrack_data["chi3"]
        geo.CG_CD_NE_CZ_diangle = dunbrack_data["chi4"]
    elif letter == "I":
        geo.N_CA_CB_CG1_diangle = dunbrack_data["chi1"]
        geo.N_CA_CB_CG2_diangle = dunbrack_data["chi1"] + 121.3
        geo.CA_CB_CG1_CD1_diangle = dunbrack_data["chi2"]
    elif letter == "L":
        geo.N_CA_CB_CG_diangle = dunbrack_data["chi1"]
        geo.CA_CB_CG_CD1_diangle = dunbrack_data["chi2"]
        geo.CA_CB_CG_CD2_diangle = dunbrack_data["chi2"] - 108.4
    elif letter == "P":
        geo.N_CA_CB_CG_diangle = dunbrack_data["chi1"]
        geo.CA_CB_CG_CD_diangle = dunbrack_data["chi2"]
    elif letter == "T":
        geo.N_CA_CB_OG1_diangle = dunbrack_data["chi1"]
        geo.N_CA_CB_CG2_diangle = dunbrack_data["chi1"] + 120.3
    elif letter == "V":
        geo.N_CA_CB_CG1_diangle = dunbrack_data["chi1"]
        geo.N_CA_CB_CG2_diangle = dunbrack_data["chi1"] + 119.5
    else:
        n = NUMBER_OF_CHI_ANGLES[letter]
        geo.inputRotamers([dunbrack_data[f"chi{i}"] for i in range(1, n + 1)])
    structure = PeptideBuilder.initialize_res(geo)
    PeptideBuilder.add_terminal_OXT(structure)
    outfile = PDBIO()
    outfile.set_structure(structure)
    pdb_file = Path(xyz_output).with_suffix(".pdb")
    outfile.save(str(pdb_file))

    # Add hydrogens according to species (charge and tautomer) with OpenMM
    pdb_wo_Hs = PDBFile(str(pdb_file))
    modeller = Modeller(pdb_wo_Hs.topology, pdb_wo_Hs.positions)
    if letter == "H":
        if charge == 0 and tautomer == "D":
            species = "HID"
        elif charge == 0 and tautomer == "E":
            species = "HIE"
        elif charge == 1:
            species = "HIP"
        elif charge == -1:
            species = "HIN"
        else:
            raise ValueError(
                f"Unknown charge/tautomer for histidine: {charge}, {tautomer}"
            )
    elif letter == "D" and charge == 0:
        species = "ASH"
    elif letter == "D" and charge == -1:
        species = "ASP"
    elif letter == "E" and charge == 0:
        species = "GLH"
    elif letter == "E" and charge == -1:
        species = "GLU"
    elif letter == "C" and charge == 0:
        species = "CYS"
    elif letter == "C" and charge == -1:
        species = "CYX"
    elif letter == "K" and charge == 1:
        species = "LYS"
    elif letter == "K" and charge == 0:
        species = "LYN"
    else:
        species = None
    modeller.addHydrogens(variants=[species])
    PDBFile.writeFile(modeller.topology, modeller.positions, file=str(pdb_file))

    # Convert PDB to XYZ file with Open Babel
    pybel.ob.obErrorLog.SetOutputLevel(
        0
    )  # suppress the "Failed to kekulize aromatic bonds" warning
    structure = next(pybel.readfile("pdb", str(pdb_file)))
    structure.write("xyz", str(xyz_output), overwrite=True)
    pdb_file.unlink()


def get_opt_structures(
    dunbrack_data: dict[str, Any],
    charge: int,
    run_folder: PathLike | str,
    rotamer_xyz: PathLike | str,
) -> tuple[
    Array1DStr,
    Array2DFloat,
    Array1DStr,
    Array2DFloat,
]:
    """Get the optimised geometries of side chain (with the backbone being replaced by an H) and rotamer
    Args:
        dunbrack_data: data with angles extracted from the Dunbrack library
        charge: charge of the rotamer
        run_folder: path of folder in which to perform the full optimisation process
        rotamer_xyz: xyz file of the whole rotamer to optimise
    Returns:
        el_whole, coord_whole, el_sidechain, coord_sidechain: elements and coordinates of the optimised structures
    """

    run_folder = Path(run_folder)
    if not run_folder.exists():
        run_folder.mkdir(parents=True)

    # Optimise the whole rotamer with constrained dihedral angles
    whole_folder = Path(run_folder) / "whole_rotamer"
    # Empty run folder (necessary for xtb)
    if whole_folder.exists():
        shutil.rmtree(whole_folder)
    whole_folder.mkdir(parents=True)

    dihedral_constraints = gen_dihedral_constraints(dunbrack_data)

    run_constraint_xtb(
        xyz_file=rotamer_xyz,
        path_run=whole_folder,
        dihedral_constraints=dihedral_constraints,
        charge=charge,
    )

    # Replace backbone by H in optimised rotamer
    sidechain_folder = Path(run_folder) / "sidechain-H"
    # Empty run folder (necessary for xtb)
    if sidechain_folder.exists():
        shutil.rmtree(sidechain_folder)
    sidechain_folder.mkdir(parents=True)
    sidechain_start_xyz = sidechain_folder / "sidechain-H_start.xyz"
    is_pro = dunbrack_data["res"] == "PRO"
    replace_backbone(whole_folder / "xtbopt.xyz", sidechain_start_xyz, is_pro=is_pro)

    # Optimise the H in the sidechain-H structure
    # Sidechain atoms are fixed except the H(s) on the same C as the H replacing the backbone
    # Atom indices are 1-based
    last_atom = get_atom_count(sidechain_start_xyz)
    if is_pro:
        # For proline, two Hs were added and need to be optimised (at first and last positions)
        fixed_atoms = [2] + list(range(5, 9))
    elif dunbrack_data["letter"] in ["I", "T", "V"]:
        # H 3 also on beta C
        fixed_atoms = [2] + list(range(4, last_atom + 1))
    else:
        # Hs 3 and 4 also on beta C
        fixed_atoms = [2] + list(range(5, last_atom + 1))
    # Dihedral constraint for the H to optimise is added
    letter = dunbrack_data["letter"]
    if letter in ["C", "S", "T", "V"]:
        sidechain_constraint = None
    else:
        sidechain_constraint = gen_sidechain_constraint(dihedral_constraints, letter)

    run_constraint_xtb(
        xyz_file=sidechain_start_xyz,
        path_run=sidechain_folder,
        fixed_atoms=fixed_atoms,
        dihedral_constraints=sidechain_constraint,
        charge=charge,
    )

    # Save the optimised sidechain-H and whole rotamer in dictionary
    el_whole, coord_whole = read_xyz(whole_folder / "xtbopt.xyz")
    el_sidechain, coord_sidechain = read_xyz(sidechain_folder / "xtbopt.xyz")

    return (
        el_whole,
        coord_whole,
        el_sidechain,
        coord_sidechain,
    )
